/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { CommonResponseData } from './commonResponseData';

export interface CommonResponse {
  code: string;
  data?: CommonResponseData;
  msg: string;
  success: string;
}
