/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { GetMinuteLine200AllOfData } from './getMinuteLine200AllOfData';

export type GetMinuteLine200AllOf = {
  data?: GetMinuteLine200AllOfData;
};
