/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { GetMinuteLine200AllOf } from './getMinuteLine200AllOf';

export type GetMinuteLine200 = CommonResponse & GetMinuteLine200AllOf;
