/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */

export type GetMinuteLineBody = {
  symbol: string;
  timestamp: number;
  pageSize: number;
};
