/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { HSIBuy } from './hSIBuy';
import type { HSIDeal } from './hSIDeal';
import type { HSISell } from './hSISell';

export interface Hsi {
  amount?: string;
  amountDecimals?: string;
  amt?: string;
  balance?: string;
  buys?: HSIBuy[];
  currency?: string;
  dealList?: HSIDeal[];
  high?: string;
  isTrade?: number;
  last?: string;
  lastCny?: string;
  low?: string;
  marketType?: string;
  name?: string;
  open?: string;
  openMarketStr?: string;
  prefixType?: string;
  priceDecimals?: number;
  rate?: string;
  sells?: HSISell[];
  symbol?: string;
  timestamp?: number;
  usdtRate?: string;
  yesClose?: string;
}
