/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */

export interface HSIBuy {
  amount?: string;
  depthRate?: number;
  price?: string;
  total?: string;
}
