/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { Kline200AllOfData } from './kline200AllOfData';

export type Kline200AllOf = {
  data?: Kline200AllOfData;
};
