/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */

export type KlineBody = {
  symbol?: string;
  klineType?: string;
  timestamp?: string;
  type?: string;
};
