/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */

export interface Kline {
  amount?: string;
  balance?: string;
  high?: string;
  last?: string;
  low?: string;
  open?: string;
  timestamp?: number;
}
