/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { Kline200AllOf } from './kline200AllOf';

export type Kline200 = CommonResponse & Kline200AllOf;
