/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */

export type Kline200AllOfData = {
  cxNum?: number;
  isEnd?: boolean;
  kline?: string;
  klineType?: string;
  symbol?: string;
};
