/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { MarketDataResponseAllOfData } from './marketDataResponseAllOfData';

export type MarketDataResponseAllOf = {
  data?: MarketDataResponseAllOfData;
};
