/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */

export type MarketDataBody = {
  sortField?: string;
  sortType?: string;
  /** stock全球指数，digital合约，spot币币 */
  tab?: string;
};
