/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { MarketDataResponseAllOf } from './marketDataResponseAllOf';

export type MarketDataResponse = CommonResponse & MarketDataResponseAllOf;
