/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { Quote } from './quote';

export type QuoteHomePageResponseAllOfData = {
  tab?: string;
  quotes?: Quote[];
};
