/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */

export interface Quote {
  amount?: string;
  amountSort?: string;
  balance?: string;
  balanceSort?: string;
  currency?: string;
  high?: string;
  low?: string;
  marketType?: string;
  name?: string;
  openMarketStr?: string;
  price?: string;
  priceCny?: string;
  rate?: string;
  sortNum?: number;
  symbol?: string;
}
