/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { QuoteReal200AllOfData } from './quoteReal200AllOfData';

export type QuoteReal200AllOf = {
  data?: QuoteReal200AllOfData;
};
