/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */

export type QuoteRealBody = {
  symbol?: string;
  klineType?: string;
  depth?: number;
};
