/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { QuoteRealResponseAllOfData } from './quoteRealResponseAllOfData';

export type QuoteRealResponseAllOf = {
  data?: QuoteRealResponseAllOfData;
};
