/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { Kline } from './kline';

export type QuoteRealResponseAllOfData = {
  klineType?: string;
  lastKline?: Kline;
  [key: string]: any;
};
