/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { QuoteRealResponseAllOf } from './quoteRealResponseAllOf';

export type QuoteRealResponse = CommonResponse & QuoteRealResponseAllOf;
