/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { QuoteHomePageResponseAllOf } from './quoteHomePageResponseAllOf';

export type QuoteHomePageResponse = CommonResponse & QuoteHomePageResponseAllOf;
