/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { QuoteReal200AllOf } from './quoteReal200AllOf';

export type QuoteReal200 = CommonResponse & QuoteReal200AllOf;
