/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */

export interface RealDeal {
  amount?: string;
  buySell?: string;
  price?: string;
  time?: number;
}
