/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Market API
 * OpenAPI spec version: 1.0
 */

export interface RealBuy {
  amount?: string;
  depthRate?: number;
  price?: string;
  total?: string;
}
