/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type AccountQueryTransferListBody = {
  pageNo: number;
  fromAccountType?: string;
  toAccountType?: string;
  userId?: string;
};
