/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { AccountRecordListItem } from './accountRecordListItem';

export type AccountRecordListResponseAllOfDataAllOf = {
  data?: AccountRecordListItem[];
};
