/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface AccountRecordListItem {
  accountType?: string;
  amount?: string;
  createTime?: string;
  createTimeMs?: string;
  id?: string;
  inOut?: string;
  lowerUserId?: string;
  remark?: string;
  state?: string;
  type?: string;
  updateTime?: string;
}
