/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { PaginationResponse } from './paginationResponse';
import type { AccountRecordListResponseAllOfDataAllOf } from './accountRecordListResponseAllOfDataAllOf';

export type AccountRecordListResponseAllOfData = PaginationResponse &
  AccountRecordListResponseAllOfDataAllOf;
