/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { AccountRecordListResponseAllOf } from './accountRecordListResponseAllOf';

export type AccountRecordListResponse = CommonResponse & AccountRecordListResponseAllOf;
