/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { AccountRecordListResponseAllOfDataAllOf } from './accountRecordListResponseAllOfDataAllOf';
import type { PaginationResponse } from './paginationResponse';

export type AccountRecordListResponseAllOfData = PaginationResponse &
  AccountRecordListResponseAllOfDataAllOf;
