/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type AccountTransferBody = {
  amount: string;
  fromAccountType: string;
  toAccountType: string;
  userId: string;
  symbol: string;
};
