/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type AddAddressBody = {
  address?: string;
  chainType?: string;
  remark?: string;
  symbol?: string;
  payPass?: string;
};
