/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface Address {
  address?: string;
  chainType?: string;
  createTime?: string;
  id?: string;
  remark?: string;
  symbol?: string;
}
