/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { AddressListResponseAllOf } from './addressListResponseAllOf';
import type { CommonResponse } from './commonResponse';

export type AddressListResponse = CommonResponse & AddressListResponseAllOf;
