/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface AdItem {
  adId?: string;
  amount?: string;
  buySell?: string;
  isOnline?: string;
  isPayAli?: string;
  isPayBank?: string;
  isPayWx?: string;
  limitRate?: string;
  maxCny?: string;
  minCny?: string;
  orderNum?: string;
  payWay?: string;
  price?: string;
  timeLimit?: string;
  userId?: string;
  userLogo?: string;
  userName?: string;
}
