/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { AllInSubscribe200AllOfData } from './allInSubscribe200AllOfData';

export type AllInSubscribe200AllOf = {
  data?: AllInSubscribe200AllOfData;
};
