/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { AllInSubscribe200AllOf } from './allInSubscribe200AllOf';
import type { CommonResponse } from './commonResponse';

export type AllInSubscribe200 = CommonResponse & AllInSubscribe200AllOf;
