/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { AllInSubscribe200AllOf } from './allInSubscribe200AllOf';

export type AllInSubscribe200 = CommonResponse & AllInSubscribe200AllOf;
