/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { ArticleHelpListResponseAllOfDataAllOfDataItem } from './articleHelpListResponseAllOfDataAllOfDataItem';

export type ArticleHelpListResponseAllOfDataAllOf = {
  data?: ArticleHelpListResponseAllOfDataAllOfDataItem[];
};
