/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { ArticleHelpListResponseAllOf } from './articleHelpListResponseAllOf';

export type ArticleHelpListResponse = CommonResponse & ArticleHelpListResponseAllOf;
