/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { ArticleHelpListResponseAllOfDataAllOf } from './articleHelpListResponseAllOfDataAllOf';
import type { PaginationResponse } from './paginationResponse';

export type ArticleHelpListResponseAllOfData = PaginationResponse &
  ArticleHelpListResponseAllOfDataAllOf;
