/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface Certification {
  certNo?: string;
  createTime?: string;
  idCertify?: string;
  limitRate?: string;
  orderNum?: string;
  realName?: string;
  reason?: string;
  securityDeposit?: string;
  state?: string;
}
