/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type ChangePhoneTwoBody = {
  newCountryCode?: string;
  newPhone?: string;
  newSmsCode?: string;
  oldPhone?: string;
  oldSmsCode?: string;
};
