/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type ChargeSubmitBody = {
  address?: string;
  amount?: string;
  chainType?: string;
  image?: string;
  symbol?: string;
};
