/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { ChargeConfigAddress } from './chargeConfigAddress';

export interface ChargeConfig {
  addressList?: ChargeConfigAddress[];
  availableAmount?: string;
  minChargeAmount?: string;
}
