/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { Address } from './address';

export interface ChargeConfig {
  addressList?: Address[];
  availableAmount?: string;
  minChargeAmount?: string;
}
