/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { ChargeConfig } from './chargeConfig';

export type ChargeConfigsResponseAllOf = {
  data?: ChargeConfig;
};
