/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { ChatListResponseAllOf } from './chatListResponseAllOf';
import type { CommonResponse } from './commonResponse';

export type ChatListResponse = CommonResponse & ChatListResponseAllOf;
