/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface ChatListItem {
  chatId?: string;
  chatTopic?: string;
  createTime?: string;
  headUrl?: string;
  mark?: string;
  name?: string;
  push?: string;
  read?: string;
  say?: string;
  toHeadUrl?: string;
  toName?: string;
  toUid?: string;
  type?: string;
  userId?: string;
  verify?: string;
}
