/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface ChatStaff {
  chatTopic?: string;
  headUrl?: string;
  type?: string;
  userId?: string;
  userName?: string;
}
