/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CoinList200AllOf } from './coinList200AllOf';
import type { CommonResponse } from './commonResponse';

export type CoinList200 = CommonResponse & CoinList200AllOf;
