/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CoinInfo200AllOfData } from './coinInfo200AllOfData';

export type CoinInfo200AllOf = {
  data?: CoinInfo200AllOfData;
};
