/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CoinList200AllOfData } from './coinList200AllOfData';

export type CoinList200AllOf = {
  data?: CoinList200AllOfData;
};
