/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface Coin {
  blockUrl?: string;
  circulateAmount?: string;
  crowdfundPrice?: string;
  currency?: string;
  desc?: string;
  isTrade?: string;
  issueAmount?: string;
  issueDate?: string;
  marketType?: string;
  maxWithdrawDecimals?: string;
  name?: string;
  officialWebUrl?: string;
  symbol?: string;
  whitePaperUrl?: string;
}
