/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { CoinListResponseAllOf } from './coinListResponseAllOf';

export type CoinListResponse = CommonResponse & CoinListResponseAllOf;
