/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CoinInfo200AllOf } from './coinInfo200AllOf';
import type { CommonResponse } from './commonResponse';

export type CoinInfo200 = CommonResponse & CoinInfo200AllOf;
