/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface CustomerServiceStaff {
  chatTopic?: string;
  headUrl?: string;
  type?: string;
  userId?: string;
  userName?: string;
}
