/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { DepositListResponseAllOf } from './depositListResponseAllOf';

export type DepositListResponse = CommonResponse & DepositListResponseAllOf;
