/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type DepositWithdrawLocalSubmitBody = {
  address?: string;
  amount?: string;
  chainType?: string;
  image?: string;
  inOut?: string;
  userId?: string;
};
