/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { DepositListResponseAllOfData } from './depositListResponseAllOfData';

export type DepositListResponseAllOf = {
  data?: DepositListResponseAllOfData;
};
