/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type DepositListBody = {
  inOut?: string;
  pageNo?: number;
  platform?: string;
  type?: number;
  userId?: string;
};
