/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type DepositListResponseAllOfDataAllOfDataItem = {
  amount?: string;
  chainType?: string;
  createTime?: string;
  dwId?: string;
  fee?: string;
  inOut?: string;
  realAmount?: string;
  state?: string;
  stateDesc?: string;
  symbol?: string;
  time?: string;
  type?: string;
  userId?: string;
};
