/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface DepositWithdrawListItem {
  address?: string;
  amount?: string;
  createTime?: string;
  dwId?: string;
  fee?: string;
  inOut?: string;
  realAmount?: string;
  sessionId?: string;
  state?: string;
  stateDesc?: string;
  subSymbol?: string;
  subTitle?: string;
  symbol?: string;
  time?: string;
  transferTime?: string;
}
