/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface FollowType {
  agentLimit?: string;
  createTime?: string;
  duration?: string;
  dvUid?: string;
  expireTime?: string;
  id?: string;
  isBind?: string;
  limit?: string;
  lossRate?: string;
  maxMultiNum?: string;
  minMultiNum?: string;
  profitRate?: string;
  tokenAmount?: string;
  updateTime?: string;
}
