/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { GetAccountHold200AllOf } from './getAccountHold200AllOf';

export type GetAccountHold200 = CommonResponse & GetAccountHold200AllOf;
