/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { GetCustomerService200AllOfData } from './getCustomerService200AllOfData';

export type GetCustomerService200AllOf = {
  data?: GetCustomerService200AllOfData;
};
