/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { Certification } from './certification';

export type GetCertificationInfo200AllOfData = {
  otcAdUrl?: string;
  otcCertification?: Certification;
};
