/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { GetCertificationInfo200AllOfData } from './getCertificationInfo200AllOfData';

export type GetCertificationInfo200AllOf = {
  data?: GetCertificationInfo200AllOfData;
};
