/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { GetCustomerServiceAnonymous200AllOfData } from './getCustomerServiceAnonymous200AllOfData';

export type GetCustomerServiceAnonymous200AllOf = {
  data?: GetCustomerServiceAnonymous200AllOfData;
};
