/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { GetCertificationInfo200AllOf } from './getCertificationInfo200AllOf';

export type GetCertificationInfo200 = CommonResponse & GetCertificationInfo200AllOf;
