/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { FollowType } from './followType';

export type GetFollowTypesResponseAllOfDataData = {
  showBind?: string;
  statementUrl?: string;
  types?: FollowType[];
};
