/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { GetSymbolMaxAmount200AllOf } from './getSymbolMaxAmount200AllOf';

export type GetSymbolMaxAmount200 = CommonResponse & GetSymbolMaxAmount200AllOf;
