/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface GetSubscribeListItem {
  alAmount?: string;
  amount?: string;
  endTime?: string;
  id?: string;
  image?: string;
  startTime?: string;
  state?: string;
  sumAmount?: string;
  summary?: string;
  symbol?: string;
  title?: string;
  progress?: string;
  rate?: string;
}
