/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { GetSubscribeListItem } from './getSubscribeListItem';

export type GetSubscribeListResponseAllOf = {
  data?: GetSubscribeListItem[];
};
