/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { GetUnreadCount200AllOfData } from './getUnreadCount200AllOfData';

export type GetUnreadCount200AllOf = {
  data?: GetUnreadCount200AllOfData;
};
