/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { GetUnreadCount200AllOfDataOtcListItem } from './getUnreadCount200AllOfDataOtcListItem';

export type GetUnreadCount200AllOfData = {
  otcCount?: string;
  otcList?: GetUnreadCount200AllOfDataOtcListItem[];
  staffCount?: string;
  sumCount?: string;
};
