/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type GetUnreadCount200AllOfDataOtcListItem = {
  orderId?: string;
  count?: string;
};
