/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { GetUnreadCount200AllOf } from './getUnreadCount200AllOf';

export type GetUnreadCount200 = CommonResponse & GetUnreadCount200AllOf;
