/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { Address } from './address';

export type GetWithdrawConfigsResponseAllOfData = {
  addressList?: Address[];
  availableAmount?: string;
  fee?: string;
  frozenAmount?: string;
};
