/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type HomeMyResponseAllOfData = {
  helpCenterUrl?: string;
  aboutUsUrl?: string;
  msgCount?: string;
  shareUrl?: string;
};
