/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { HomeMyResponseAllOfData } from './homeMyResponseAllOfData';

export type HomeMyResponseAllOf = {
  data?: HomeMyResponseAllOfData;
};
