/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { Banner } from './banner';
import type { HomeCropMeResponseAllOfDataPlatformData } from './homeCropMeResponseAllOfDataPlatformData';
import type { Notice } from './notice';
import type { ScoreRank } from './scoreRank';

export type HomeCropMeResponseAllOfData = {
  banner?: Banner[];
  noticeList?: Notice[];
  platformData?: HomeCropMeResponseAllOfDataPlatformData;
  scoreRank?: ScoreRank[];
};
