/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { HomeConfig200AllOfDataBannerItem } from './homeConfig200AllOfDataBannerItem';

export type HomeConfig200AllOfData = {
  downloadUrl?: string;
  banner?: HomeConfig200AllOfDataBannerItem[];
};
