/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { HomeConfig200AllOfData } from './homeConfig200AllOfData';

export type HomeConfig200AllOf = {
  data?: HomeConfig200AllOfData;
};
