/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type HomeConfig200AllOfDataBannerItem = {
  bannerId?: string;
  cls?: string;
  createTime?: string;
  downTime?: string;
  imageUrl?: string;
  lang?: string;
  params?: string;
  pkg?: string;
  position?: string;
  pview?: string;
  sortNum?: string;
  state?: string;
  type?: string;
  upTime?: string;
  videoUrl?: string;
};
