/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { Banner } from './banner';

export type HomeConfig200AllOfData = {
  banner?: Banner[];
  downloadUrl?: string;
};
