/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { IdentityAuth } from './identityAuth';

export type IdentityAuthResponseAllOfData = {
  identityAuth?: IdentityAuth;
};
