/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type IdentitySubmitBody = {
  backImgUrl: string;
  certNo: string;
  frontImgUrl: string;
  name: string;
};
