/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { IdentityConfig200AllOfDataItem } from './identityConfig200AllOfDataItem';

export type IdentityConfig200AllOf = {
  data?: IdentityConfig200AllOfDataItem[];
};
