/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { IdentityConfig200AllOfDataBannerItem } from './identityConfig200AllOfDataBannerItem';

export type IdentityConfig200AllOfData = {
  banner?: IdentityConfig200AllOfDataBannerItem[];
};
