/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { IdentityGet200AllOf } from './identityGet200AllOf';

export type IdentityGet200 = CommonResponse & IdentityGet200AllOf;
