/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface IdentityAuth {
  backImgUrl?: string;
  certNo?: string;
  checkMsg?: string;
  createTime?: string;
  frontImgUrl?: string;
  name?: string;
  state?: string;
  stateDesc?: string;
  userId?: string;
}
