/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { InviteHomeResponseAllOfData } from './inviteHomeResponseAllOfData';

export type InviteHomeResponseAllOf = {
  data?: InviteHomeResponseAllOfData;
};
