/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type InviteHomeResponseAllOfDataInviteListItem = {
  amount?: string;
  inviteCode?: string;
  inviteUserId?: string;
  status?: string;
  userId?: string;
};
