/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { InviteHomeResponseAllOfDataInviteListItem } from './inviteHomeResponseAllOfDataInviteListItem';

export type InviteHomeResponseAllOfData = {
  inviteCount?: string;
  teamCount?: string;
  inviteCodePrice?: string;
  sumAmount?: string;
  inviteList?: InviteHomeResponseAllOfDataInviteListItem[];
};
