/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { IsOptional200AllOfData } from './isOptional200AllOfData';

export type IsOptional200AllOf = {
  data?: IsOptional200AllOfData;
};
