/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { ListAccountTypeResponseAllOfData } from './listAccountTypeResponseAllOfData';

export type ListAccountTypeResponseAllOf = {
  data?: ListAccountTypeResponseAllOfData;
};
