/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type LoginBody = {
  dragImgKey: string;
  email?: string;
  locationx?: number;
  phone?: string;
  platform?: string;
  smsCode?: string;
  type?: number;
  userPass?: string;
};
