/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { Login200AllOf } from './login200AllOf';

export type Login200 = CommonResponse & Login200AllOf;
