/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { Login200AllOfData } from './login200AllOfData';

export type Login200AllOf = {
  data?: Login200AllOfData;
};
