/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { MessageFindResponseAllOfDataAllOfDataItem } from './messageFindResponseAllOfDataAllOfDataItem';

export type MessageFindResponseAllOfDataAllOf = {
  data?: MessageFindResponseAllOfDataAllOfDataItem[];
};
