/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface MyPaymentListItem {
  bankName?: string;
  paymentId?: string;
  receiptLogo?: string;
  receiptName?: string;
  receiptNo?: string;
  receiptType?: string;
  receiptTypeValue?: string;
  sort?: string;
}
