/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface Notice {
  articleId?: string;
  createTime?: string;
  isTop?: string;
  title?: string;
  type?: string;
  url?: string;
}
