/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface OrderToPayResult {
  alertTip?: string;
  amount?: string;
  bankName?: string;
  chatTopic?: string;
  createTime?: string;
  currencySign?: string;
  orderId?: string;
  paySecondTime?: string;
  payTip?: string;
  price?: string;
  receiptLogo?: string;
  receiptName?: string;
  receiptNo?: string;
  receiptType?: string;
  receiptTypeValue?: string;
  showRealName?: string;
  showUserId?: string;
  showUserLogo?: string;
  showUserName?: string;
  showUserTip?: string;
  state?: string;
  stateValue?: string;
  tolPrice?: string;
}
