/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface Order {
  adId?: string;
  alertTip?: string;
  amount?: string;
  buySell?: string;
  buySellValue?: string;
  buyUserId?: string;
  chatTopic?: string;
  createTime?: string;
  currencySign?: string;
  orderId?: string;
  paySecondTime?: string;
  price?: string;
  receiptName?: string;
  sellUserId?: string;
  showPayWay?: string;
  showRealName?: string;
  showUserId?: string;
  showUserLogo?: string;
  showUserName?: string;
  state?: string;
  stateTip?: string;
  stateValue?: string;
  tolPrice?: string;
}
