/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { OtcAddMyAd200AllOfData } from './otcAddMyAd200AllOfData';

export type OtcAddMyAd200AllOf = {
  data?: OtcAddMyAd200AllOfData;
};
