/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type OtcAddMyAdBody = {
  amount?: string;
  buySell?: string;
  content?: string;
  maxCny?: string;
  minCny?: string;
  payWay?: string;
  price?: string;
};
