/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { OtcCreateOrder200AllOf } from './otcCreateOrder200AllOf';

export type OtcCreateOrder200 = CommonResponse & OtcCreateOrder200AllOf;
