/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { OtcCreateOrder200AllOfData } from './otcCreateOrder200AllOfData';

export type OtcCreateOrder200AllOf = {
  data?: OtcCreateOrder200AllOfData;
};
