/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type OtcCreateOrderBody = {
  adId: string;
  amount: string;
  buySell: string;
  price: string;
  showReceiptType?: string;
};
