/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { AdItem } from './adItem';

export type OtcFindMyAdList200AllOfData = {
  myAdList?: AdItem[];
};
