/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type OtcFindOrderListBody = {
  buySell?: string;
  state?: string;
  pageNo?: number;
};
