/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { OtcFindOrderListResponseAllOf } from './otcFindOrderListResponseAllOf';

export type OtcFindOrderListResponse = CommonResponse & OtcFindOrderListResponseAllOf;
