/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { OtcFindMyAdList200AllOf } from './otcFindMyAdList200AllOf';

export type OtcFindMyAdList200 = CommonResponse & OtcFindMyAdList200AllOf;
