/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { OtcFindAdListResponseAllOfDataAllOf } from './otcFindAdListResponseAllOfDataAllOf';
import type { PaginationResponse } from './paginationResponse';

export type OtcFindAdListResponseAllOfData = PaginationResponse &
  OtcFindAdListResponseAllOfDataAllOf;
