/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type OtcFindAdListBody = {
  buySell?: string;
  currencyType?: string;
  filterCny?: string;
  filterPayWay?: string;
  pageNo?: string;
  type?: string;
};
