/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { PaginationResponse } from './paginationResponse';
import type { OtcFindOrderListResponseAllOfDataAllOf } from './otcFindOrderListResponseAllOfDataAllOf';

export type OtcFindOrderListResponseAllOfData = PaginationResponse &
  OtcFindOrderListResponseAllOfDataAllOf;
