/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { OtcGetCertificationInfo200AllOfData } from './otcGetCertificationInfo200AllOfData';

export type OtcGetCertificationInfo200AllOf = {
  data?: OtcGetCertificationInfo200AllOfData;
};
