/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { OtcGetAdPrice200AllOfData } from './otcGetAdPrice200AllOfData';

export type OtcGetAdPrice200AllOf = {
  data?: OtcGetAdPrice200AllOfData;
};
