/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { OtcGetMyAdInfo200AllOf } from './otcGetMyAdInfo200AllOf';

export type OtcGetMyAdInfo200 = CommonResponse & OtcGetMyAdInfo200AllOf;
