/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { OtcGetOrderDetailResponseAllOfData } from './otcGetOrderDetailResponseAllOfData';

export type OtcGetOrderDetailResponseAllOf = {
  data?: OtcGetOrderDetailResponseAllOfData;
};
