/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { Certification } from './certification';

export type OtcGetCertificationInfo200AllOfData = {
  otcAdUrl?: string;
  otcCertification?: Certification;
};
