/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface OtcOrderListItem {
  adId?: string;
  amount?: string;
  appealUserId?: string;
  buyAgencyCode?: string;
  buyBankName?: string;
  buyMemberCode?: string;
  buyReceiptName?: string;
  buyReceiptNo?: string;
  buySell?: string;
  buySellValue?: string;
  buyUserId?: string;
  chatTopic?: string;
  createTime?: string;
  currencySign?: string;
  doneTime?: string;
  expireTime?: string;
  isAdSell?: string;
  orderId?: string;
  price?: string;
  sellAgencyCode?: string;
  sellBankName?: string;
  sellMemberCode?: string;
  sellPayWay?: string;
  sellReceiptName?: string;
  sellReceiptNo?: string;
  sellUserId?: string;
  showPaymentId?: string;
  state?: string;
  stateValue?: string;
  synVersion?: string;
  tolPrice?: string;
}
