/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type OtcSubmitAppealBody = {
  image1Url?: string;
  image2Url?: string;
  message?: string;
  orderId?: string;
  reason?: string;
};
