/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type OtcToPayOrderBody = {
  orderId: string;
  showPaymentId: string;
  showUserId: string;
};
