/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { OutHoldAmountResponseAllOfData } from './outHoldAmountResponseAllOfData';

export type OutHoldAmountResponseAllOf = {
  data?: OutHoldAmountResponseAllOfData;
};
