/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type PersonalTrendChartBody = {
  targetUid: string;
  /** month month3 month6 year */
  timeType?: string;
  /** 1 业绩走势  2跟单人气  3交易次数  4累计盈亏 */
  type?: string;
};
