/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { PersonalTrendChartResponseAllOfData } from './personalTrendChartResponseAllOfData';

export type PersonalTrendChartResponseAllOf = {
  data?: PersonalTrendChartResponseAllOfData;
};
