/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface PledgeListItem {
  dayProfitRate?: string;
  duration?: string;
  endTime?: string;
  id?: string;
  minCount?: string;
  pledgeName?: string;
  profitRate?: string;
  returnSymbol?: string;
  sort?: string;
  startTime?: string;
  status?: string;
  symbol?: string;
}
