/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface PledgeRecord {
  count?: string;
  duration?: string;
  endTime?: string;
  id?: string;
  preProfit?: string;
  pledgeId?: string;
  profit?: string;
  profitRate?: string;
  startTime?: string;
  status?: string;
  symbol?: string;
}
