/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface Position {
  accountType?: string;
  accountTypeName?: string;
  airDropAmount?: string;
  amount?: string;
  availableAmount?: string;
  buySell?: string;
  buySellValue?: string;
  closeDetails?: string;
  closePrice?: string;
  dvLossRate?: string;
  dvProfitRate?: string;
  dvUid?: string;
  followUid?: string;
  frozenAmount?: string;
  openHand?: string;
  openPrice?: string;
  openTime?: string;
  orderId?: string;
  price?: string;
  profit?: string;
  profitRate?: string;
  subAmount?: string;
  symbol?: string;
  usdtAmount?: string;
}
