/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type ProOrderCheckOutUsdtBody = {
  symbol?: string;
  price?: string;
  buySell?: string;
  /** 输入的usdt数量 */
  hand?: string;
  multiNum?: string;
  orderType?: string;
  type?: string;
};
