/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface ProOrderDetail {
  amount?: string;
  availableAmount?: string;
  last?: string;
  price?: string;
  priceDecimals?: string;
  profit?: string;
  profitRate?: string;
  rate?: string;
  symbol?: string;
  usdtAmount?: string;
}
