/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { ProOrderCheckOutUsdt200AllOfData } from './proOrderCheckOutUsdt200AllOfData';

export type ProOrderCheckOutUsdt200AllOf = {
  data?: ProOrderCheckOutUsdt200AllOfData;
};
