/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type ProOrderQueryListItemCloseDetailsItem = {
  closeBail?: string;
  closeFee?: string;
  closeHand?: string;
  closePrice?: string;
  closeTime?: string;
  dvForLossShare?: string;
  dvForProfitShare?: string;
  lossShare?: string;
  profit?: string;
  profitShare?: string;
};
