/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { ProOrder } from './proOrder';
import type { ProOrderData } from './proOrderData';

export type ProOrderDetailResponseAllOfData = {
  order?: ProOrder;
  data?: ProOrderData;
};
