/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type ProOrderCheckOutBody = {
  symbol?: string;
  price?: string;
  buySell?: string;
  hand?: string;
  multiNum?: string;
  orderType?: string;
  type?: string;
};
