/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { PaginationResponse } from './paginationResponse';
import type { ProOrderQueryListResponseAllOfDataAllOf } from './proOrderQueryListResponseAllOfDataAllOf';

export type ProOrderQueryListResponseAllOfData = PaginationResponse &
  ProOrderQueryListResponseAllOfDataAllOf;
