/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type ProOrderCloseDetailsItem = {
  profit?: string;
  closePrice?: string;
  closeHand?: string;
  closeFee?: string;
  closeTime?: string;
  profitShare?: string;
  lossShare?: string;
};
