/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { ProOrderCheckOut200AllOfData } from './proOrderCheckOut200AllOfData';

export type ProOrderCheckOut200AllOf = {
  data?: ProOrderCheckOut200AllOfData;
};
