/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { ProOrderCheckOutUsdt200AllOf } from './proOrderCheckOutUsdt200AllOf';

export type ProOrderCheckOutUsdt200 = CommonResponse & ProOrderCheckOutUsdt200AllOf;
