/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type ProOrderCheckOutUsdt200AllOfData = {
  /** 可输入的最大usdt数量,20% 40%等取这个值的乘积 */
  maxOpenBail?: string;
  /** 可以买入的币的数量，调用/pro/order/open.do这个接口时的hand参数取这个值 */
  openHand?: string;
};
