/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type ProOrderConfigResponseAllOfData = {
  accountName?: string;
  accountType?: string;
  initHandList?: number[];
  multiNumList?: number[];
  openFeeScale?: string;
  priceDecimals?: string;
  usdtRate?: string;
  openRateList?: number[];
};
