/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface ProOrder {
  buySell?: string;
  buySellValue?: string;
  closeDetails?: string;
  closeDone?: string;
  closeFee?: string;
  closePrice?: string;
  closeState?: string;
  closeStateDesc?: string;
  closeTime?: string;
  last?: string;
  multiNum?: string;
  nowStateDesc?: string;
  openBail?: string;
  openDone?: string;
  openFee?: string;
  openHand?: string;
  openPrice?: string;
  openState?: string;
  openStateDesc?: string;
  openTime?: string;
  orderId?: string;
  price?: string;
  priceDecimals?: string;
  profit?: string;
  profitRate?: string;
  rate?: string;
  stopLossPrice?: string;
  stopWinPrice?: string;
  symbol?: string;
}
