/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type ProOrderOpenBody = {
  buySell?: string;
  hand?: string;
  multiNum?: string;
  orderType?: string;
  price?: string;
  symbol?: string;
  type?: string;
};
