/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type ProOrderQueryListBody = {
  accountType?: string;
  buySell?: string;
  isDone?: string;
  pageNo?: string;
  type?: string;
  symbol?: string;
  orderState?: string;
};
