/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type QueryTransferListResponseAllOfDataAllOfDataItem = {
  amount?: string;
  createTime?: string;
  fromAccountType?: string;
  toAccountType?: string;
  transferId?: string;
  typeValue?: string;
  userId?: string;
};
