/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { QueryTransferListResponseAllOf } from './queryTransferListResponseAllOf';

export type QueryTransferListResponse = CommonResponse & QueryTransferListResponseAllOf;
