/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { PledgeRecord } from './pledgeRecord';

export type RecordListPledgesResponseAllOf = {
  data?: PledgeRecord[];
};
