/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { Register200AllOf } from './register200AllOf';

export type Register200 = CommonResponse & Register200AllOf;
