/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { Register200AllOfData } from './register200AllOfData';

export type Register200AllOf = {
  data?: Register200AllOfData;
};
