/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { UserInfo } from './userInfo';

export type Register200AllOfData = {
  token?: string;
  user?: UserInfo;
};
