/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface ScoreRank {
  correctRate?: string;
  days?: string;
  entryTime?: string;
  expireTime?: string;
  headUrl?: string;
  isExpireTime?: string;
  maxMultiNum?: string;
  monthProfit?: string;
  subIsFee?: string;
  totalProfit?: string;
  userId?: string;
  userName?: string;
}
