/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface SearchResultListItem {
  marketType?: string;
  name?: string;
  prefixType?: string;
  symbol?: string;
  symbolPair?: string;
  type?: string;
}
