/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { SetPayPass200AllOfData } from './setPayPass200AllOfData';

export type SetPayPass200AllOf = {
  data?: SetPayPass200AllOfData;
};
