/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { SetPayPass200AllOf } from './setPayPass200AllOf';

export type SetPayPass200 = CommonResponse & SetPayPass200AllOf;
