/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type SmsGetBody = {
  countryCode: string;
  dragImgKey?: string;
  locationx?: number;
  sendAddr: string;
  type: number;
};
