/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface SubscribeDetail {
  alCount?: string;
  allSum?: string;
  authorSummary?: string;
  condition?: string;
  content?: string;
  description?: string;
  endTime?: string;
  expCountry?: string;
  image?: string;
  liftBanTime?: string;
  min?: string;
  rate?: string;
  startTime?: string;
  state?: string;
  sum?: string;
  sumAlCount?: string;
  summary?: string;
  symbol?: string;
  title?: string;
  tradeTime?: string;
  userCount?: string;
  warning?: string;
  progress?: string;
}
