/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export type SubscribeRecordListResponseAllOfDataAllOfDataItem = {
  id?: string;
  count?: number;
  time?: string;
  symbol?: string;
  title?: string;
  state?: string;
  luckyCount?: string;
  tradeTime?: string;
  stateDesc?: string;
  paidAmount?: string;
  unpaidAmount?: string;
};
