/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface SymbolListItem {
  /** 委托 */
  frozenAmount?: string;
  /** 可用 */
  holdAmount?: string;
  /** 总资产 */
  sumAmount?: string;
  symbol?: string;
  /** 折合 */
  usdtAmount?: string;
}
