/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { ChatStaff } from './chatStaff';
import type { OrderToPayResult } from './orderToPayResult';

export type ToPayOrderResponseAllOfData = {
  chatStaff?: ChatStaff;
  orderToPayResult?: OrderToPayResult;
};
