/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { ToPayOrderResponseAllOf } from './toPayOrderResponseAllOf';

export type ToPayOrderResponse = CommonResponse & ToPayOrderResponseAllOf;
