/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface UserRadar {
  attentionNum?: string;
  correctRate?: string;
  days?: string;
  describes?: string;
  dvLossRate?: string;
  dvProfitRate?: string;
  entryTime?: string;
  expireTime?: string;
  followAutoBind?: string;
  followDigitalAssets?: string;
  followNotice?: string;
  followProfitRate?: string;
  followStockAssets?: string;
  headUrl?: string;
  isAgentOnly?: string;
  isExpireTime?: string;
  isOnline?: string;
  maxMultiNum?: string;
  monthProfit?: string;
  myIsAttention?: string;
  myIsFollow?: string;
  radarFollowBalance?: string;
  radarFollowBalanceWeight?: string;
  radarFollowNum?: string;
  radarFollowNumWeight?: string;
  radarFollowProfitRate?: string;
  radarFollowProfitRateWeight?: string;
  radarFollowWinRate?: string;
  radarFollowWinRateWeight?: string;
  radarProfitRate?: string;
  radarProfitRateWeight?: string;
  realAttentionNum?: string;
  realFollowCount?: string;
  recommend?: string;
  subFee?: string;
  subFeeType?: string;
  subFeeTypeName?: string;
  subFeeTypeUnit?: string;
  subIsFee?: string;
  tolRadarWeight?: string;
  totalProfit?: string;
  userId?: string;
  userName?: string;
}
