/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */
import type { CommonResponse } from './commonResponse';
import type { UserInfoResponseAllOf } from './userInfoResponseAllOf';

export type UserInfoResponse = CommonResponse & UserInfoResponseAllOf;
