/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Title
 * OpenAPI spec version: 1.0
 */

export interface UserInfo {
  adminType?: string;
  agencyCode?: string;
  countryCode?: string;
  createTime?: string;
  describes?: string;
  email?: string;
  headUrl?: string;
  idCertify?: string;
  inviteUid?: string;
  isLock?: string;
  isMark?: string;
  isStop?: string;
  isVip?: string;
  lastIp?: string;
  lastLogin?: string;
  memberCode?: string;
  passErrNum?: string;
  phone?: string;
  payPass?: string;
  regPlatform?: string;
  sex?: string;
  synSign?: string;
  synVersion?: string;
  userId?: string;
  userName?: string;
  userPass?: string;
  verifySql?: string;
  verifySqlTime?: string;
  version?: string;
}
